// <auto-generated />
using System;
using Domain.ClimaContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20221030211249_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Climate", b =>
                {
                    b.Property<int>("IdClima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClima");

                    b.ToTable("Climates");
                });

            modelBuilder.Entity("Domain.Entities.Temp", b =>
                {
                    b.Property<int>("IdTemp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdClima")
                        .HasColumnType("int");

                    b.Property<int?>("humidity")
                        .HasColumnType("int");

                    b.Property<int?>("pressure")
                        .HasColumnType("int");

                    b.Property<double>("temp_max")
                        .HasColumnType("float");

                    b.Property<double>("temp_min")
                        .HasColumnType("float");

                    b.HasKey("IdTemp");

                    b.HasIndex("IdClima");

                    b.ToTable("Temp");
                });

            modelBuilder.Entity("Domain.Entities.Temp", b =>
                {
                    b.HasOne("Domain.Entities.Climate", "Climate")
                        .WithMany("Temp")
                        .HasForeignKey("IdClima");
                });
#pragma warning restore 612, 618
        }
    }
}
